//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class C27_02_Book_
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookSummary { get; set; }
        public string BookQualitiStranica { get; set; }
        public string BookAuthor { get; set; }
    }
}
